LANG_CODES = {
    "American English": "a",
    "British English":  "b",
    "Hindi":            "h",
    "French":           "f",
    "Italian":          "i",
    "Japanese":         "j",
    "Mandarin Chinese": "z",
    "Spanish":          "e",
    "Br. Portuguese":   "p",
}

LANG_FLAGS = {
    "American English": "🇺🇸",
    "British English":  "🇬🇧",
    "Hindi":            "🇮🇳",
    "French":           "🇫🇷",
    "Italian":          "🇮🇹",
    "Japanese":         "🇯🇵",
    "Mandarin Chinese": "🇨🇳",
    "Spanish":          "🇪🇸",
    "Br. Portuguese":   "🇧🇷",
}

VOICES = {
    "American English": [
        ("af_heart",   "Heart ♀ ❤️  · A"),
        ("af_bella",   "Bella ♀ 🔥 · A-"),
        ("af_nicole",  "Nicole ♀ 🎧 · B-"),
        ("af_aoede",   "Aoede ♀ · C+"),
        ("af_kore",    "Kore ♀ · C+"),
        ("af_sarah",   "Sarah ♀ · C+"),
        ("af_alloy",   "Alloy ♀ · C"),
        ("af_nova",    "Nova ♀ · C"),
        ("af_sky",     "Sky ♀ · C-"),
        ("am_fenrir",  "Fenrir ♂ · C+"),
        ("am_michael", "Michael ♂ · C+"),
        ("am_puck",    "Puck ♂ · C+"),
        ("am_echo",    "Echo ♂ · D"),
        ("am_eric",    "Eric ♂ · D"),
        ("am_liam",    "Liam ♂ · D"),
        ("am_adam",    "Adam ♂ · F+"),
    ],
    "British English": [
        ("bf_emma",     "Emma ♀ · B-"),
        ("bf_isabella", "Isabella ♀ · C"),
        ("bf_alice",    "Alice ♀ · D"),
        ("bf_lily",     "Lily ♀ · D"),
        ("bm_fable",    "Fable ♂ · C"),
        ("bm_george",   "George ♂ · C"),
        ("bm_lewis",    "Lewis ♂ · D+"),
        ("bm_daniel",   "Daniel ♂ · D"),
    ],
    "Hindi": [
        ("hf_alpha", "Alpha ♀ · C"),
        ("hf_beta",  "Beta ♀ · C"),
        ("hm_omega", "Omega ♂ · C"),
        ("hm_psi",   "Psi ♂ · C"),
    ],
    "French": [
        ("ff_siwis", "Siwis ♀ · B-"),
    ],
    "Italian": [
        ("if_sara",   "Sara ♀ · C"),
        ("im_nicola", "Nicola ♂ · C"),
    ],
    "Japanese": [
        ("jf_alpha",      "Alpha ♀ · C+"),
        ("jf_gongitsune", "Gongitsune ♀ · C"),
        ("jf_tebukuro",   "Tebukuro ♀ · C"),
        ("jm_kumo",       "Kumo ♂ · C-"),
    ],
    "Mandarin Chinese": [
        ("zf_xiaobei",  "Xiaobei ♀"),
        ("zf_xiaoni",   "Xiaoni ♀"),
        ("zf_xiaoxiao", "Xiaoxiao ♀"),
        ("zf_xiaoyi",   "Xiaoyi ♀"),
        ("zm_yunjian",  "Yunjian ♂"),
        ("zm_yunxi",    "Yunxi ♂"),
        ("zm_yunxia",   "Yunxia ♂"),
        ("zm_yunyang",  "Yunyang ♂"),
    ],
    "Spanish": [
        ("ef_dora",  "Dora ♀"),
        ("em_alex",  "Alex ♂"),
        ("em_santa", "Santa ♂"),
    ],
    "Br. Portuguese": [
        ("pf_dora",  "Dora ♀"),
        ("pm_alex",  "Alex ♂"),
        ("pm_santa", "Santa ♂"),
    ],
}
